language: go

services:
  - mysql
  - postgresql
env:
  - SUBSTANCE_MYSQL="root@tcp(127.0.0.1:3306)/delivery" SUBSTANCE_PGSQL="postgres://travis_test:password@127.0.0.1:5432/postgres"
before_install:
  - mysql -e 'CREATE DATABASE delivery;'
  - mysql -e 'use delivery; CREATE TABLE Persons (ID int PRIMARY KEY,LastName varchar(255),FirstName varchar(255),Address varchar(255),City varchar(255));CREATE TABLE Orders (OrderID int UNIQUE NOT NULL,OrderNumber int NOT NULL,PersonID int DEFAULT NULL,PRIMARY KEY (OrderID),FOREIGN KEY (PersonID) REFERENCES Persons(ID));CREATE TABLE AntiOrders (AntiOrderID int UNIQUE NOT NULL,AntiOrderNumber int NOT NULL,PersonID int UNIQUE DEFAULT NULL,PRIMARY KEY (AntiOrderID),FOREIGN KEY (PersonID) REFERENCES Persons(ID));'
  - psql -c "CREATE USER travis_test WITH PASSWORD 'password';" -U postgres
  - psql -c "CREATE TABLE Persons (ID int PRIMARY KEY,LastName varchar(255),FirstName varchar(255),Address varchar(255),City varchar(255));CREATE TABLE Orders (OrderID int UNIQUE NOT NULL,OrderNumber int NOT NULL,PersonID int DEFAULT NULL,PRIMARY KEY (OrderID),FOREIGN KEY (PersonID) REFERENCES Persons(ID));CREATE TABLE AntiOrders (AntiOrderID int UNIQUE NOT NULL,AntiOrderNumber int NOT NULL,PersonID int UNIQUE DEFAULT NULL,PRIMARY KEY (AntiOrderID),FOREIGN KEY (PersonID) REFERENCES Persons(ID));" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO travis_test;" -U postgres

script:
  - go test -v ./providers/mysqlsubstance/ -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash)
  - go test -v ./providers/pgsqlsubstance/ -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash)
  - go test -v ./substancegen/ -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash)